<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <OutputType Condition="'$(Configuration)' != 'Debug' AND $([MSBuild]::IsOSPlatform('windows'))">WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>GlazeWM-Tray</AssemblyName>
    <ApplicationManifest Condition="$([MSBuild]::IsOSPlatform('windows'))">app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>link</TrimMode>
    <BuiltInComInteropSupport Condition="$([MSBuild]::IsOSPlatform('windows'))">true</BuiltInComInteropSupport>
    <ApplicationIcon Condition="$([MSBuild]::IsOSPlatform('windows'))">Assets\icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Helpers.fs" />
    <Compile Include="AboutPanel.fs" />
    <Compile Include="QueryPanel.fs" />
    <Compile Include="MainView.fs" />
    <Compile Include="App.fs" />
    <Compile Include="Program.fs" />
    <Content Include="Assets\*.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lib\Lib.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.FuncUI" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" />
    <PackageReference Include="Huskui.Avalonia" />
    <PackageReference Include="MessageBox.Avalonia" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="Tmds.DBus.Protocol" /> <!-- should be removed after upgrading avalonia -->
  </ItemGroup>
</Project>
