<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>GlazeWM-Tray</AssemblyName>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
  </PropertyGroup>
 
  <ItemGroup>
    <Content Include="Assets\*.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.FuncUI" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Serilog.Sinks.Console" />
  </ItemGroup>
</Project>
