<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>GlazeWM-Tray</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Assets\*.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Compile Include="Program.fs" />
  </ItemGroup>
  
  <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>
