<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="FsToolkit.ErrorHandling" Version="5.2.0" />
    <PackageVersion Include="MessageBox.Avalonia" Version="3.3.1.1" />
    <PackageVersion Include="Microsoft.Toolkit.Uwp.Notifications" Version="7.1.3" />
    <PackageVersion Include="Serilog" Version="4.3.1" />
    <PackageVersion Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageVersion Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageVersion Include="Farse" Version="0.8.0" />
    <!-- Avalonia -->
    <PackageVersion Include="Avalonia.Desktop" Version="11.3.12" />
    <PackageVersion Include="Avalonia.FuncUI" Version="1.5.2" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="11.3.12" />
    <PackageVersion Include="Avalonia.Fonts.Inter" Version="11.3.12" />
    <PackageVersion Include="Avalonia.Diagnostics" Version="11.3.12" />
    <!-- Testing Dependencies-->
    <PackageVersion Include="coverlet.collector" Version="8.0.1" />
    <PackageVersion Include="Fleck" Version="1.2.0" />
    <PackageVersion Include="FsUnit" Version="7.1.1" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
    <PackageVersion Include="NUnit" Version="4.5.1" />
    <PackageVersion Include="NUnit.Analyzers" Version="4.12.0" />
    <PackageVersion Include="NUnit3TestAdapter" Version="6.2.0" />
  </ItemGroup>
</Project>